format: yamanifest
version: 1.0
---
work/mitgcmuv:
  fullpath: /home/156/cy8964/MITgcm/verification/ocean1/run2/mitgcmuv
  hashes:
    binhash: a192ea0f4ffecffabff2751a98a5ddef
    md5: 29c891d81639c9e3aa0416c63f97a16d
